package minerva;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.*;
import java.util.stream.Collectors;

import minerva.common.Keyword;
import minerva.exception.MinervaArgumentException;
import minerva.storage.Storage;
import minerva.task.Deadline;
import minerva.task.Event;
import minerva.task.Task;
import minerva.task.TaskList;
import minerva.task.ToDo;
import minerva.ui.Ui;

/**
 * Manages Minerva commands and task storage.
 */
public class Minerva {
    private static final String FILE_PATH = "." + File.separator + "data"
            + File.separator + "minerva.txt";

    private final Storage storage;
    private TaskList tasks;
    private TaskList foundTasks;
    private final Ui ui;
    private Deque<TaskList> deque = new ArrayDeque<>();

    /**
     * Loads saved tasks from the specified file.
     *
     * @param filePath path of the task storage file
     */
    public Minerva(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);

        try {
            tasks = new TaskList(storage.load());
        } catch (FileNotFoundException | SecurityException e) {
            ui.showLoadingError();
            tasks = new TaskList();
        }
    }

    /**
     * Processes one command for the graphical interface.
     *
     * @param input command entered by the user
     * @return response to display
     */
    public String getResponse(String input) {
        return processCommand(input);
    }

    /**
     * Processes one Minerva command and returns its response.
     *
     * @param input command entered by the user
     * @return response generated by the command
     */
    public String processCommand(String input) {
        if (input == null || input.isBlank()) {
            return "No worries! Please enter a command so I can help.";
        }

        String fullCommand = input.trim();
        String[] parts = fullCommand.split("\\s+", 2);
        String command = parts[0].toLowerCase();

        Keyword keyword = switch (command) {
            case "bye" -> Keyword.BYE;
            case "list" -> Keyword.LIST;
            case "mark" -> Keyword.MARK;
            case "unmark" -> Keyword.UNMARK;
            case "todo" -> Keyword.TODO;
            case "deadline" -> Keyword.DEADLINE;
            case "event" -> Keyword.EVENT;
            case "delete" -> Keyword.DELETE;
            case "task" -> Keyword.TASK;
            case "help" -> Keyword.HELP;
            case "find" -> Keyword.FIND;
            case "undo" -> Keyword.UNDO;
            default -> Keyword.UNKNOWN;
        };

        String argument = parts.length > 1 ? parts[1].trim() : "";

        return switch (keyword) {
            case BYE -> "Bye. And I hope to see you again soon!";

            case LIST -> listTasks();

            case FIND -> findTasks(argument);

            case HELP -> showHelp();

            case MARK -> markTask(argument);

            case UNMARK -> unmarkTask(argument);

            case TODO -> addTodo(argument);

            case DEADLINE -> addDeadline(argument);

            case EVENT -> addEvent(argument);

            case DELETE -> deleteTask(argument);

            case TASK -> addTask(fullCommand);

            case UNDO -> undo();

            case UNKNOWN -> "I’m sorry, I didn’t recognize that command. Type help to see what I can do.";
        };
    }

    /**
     * Runs the console version of Minerva.
     */
    public void run() {
        ui.showWelcome();
        boolean isExit = false;

        while (!isExit) {
            ui.showPrompt();
            String command;
            try {
                command = ui.readCommand();
            } catch (NoSuchElementException e) {
                ui.showFarewell();
                break;
            }
            String response = processCommand(command);
            ui.showMessage(response);
            isExit = command.trim().equalsIgnoreCase("bye");
        }
    }

    /**
     * Lists all stored tasks.
     *
     * @return formatted task list
     */
    private String listTasks() {
        StringBuilder response = new StringBuilder("Here are the tasks in your list:");

        for (int i = 0; i < tasks.getSize(); i++) {
            response.append("\n").append(i + 1).append(". ").append(tasks.get(i));
        }

        return response.toString();
    }

    /**
     * Finds tasks containing the specified word.
     *
     * @param word search term
     * @return matching tasks
     */
    private String findTasks(String word) {
        if (word.isBlank()) {
            return "Please provide a word to search for.";
        }

        ArrayList<Task> matchingTasks = tasks.getTasks().stream()
                .filter(task -> task.containsWord(word))
                .collect(Collectors.toCollection(ArrayList::new));
        foundTasks = new TaskList(matchingTasks);

        StringBuilder response = new StringBuilder(
                "Here are the matching tasks in your list:\n"
                        + "Please do not delete/mark/unmark with this found index");

        for (int i = 0; i < foundTasks.getSize(); i++) {
            response.append("\n").append(i + 1).append(".").append(foundTasks.get(i));
        }

        return response.toString();
    }

    /**
     * Lists all available commands.
     *
     * @return available commands
     */
    private String showHelp() {
        StringBuilder response = new StringBuilder("Here are the available functions:");

        Arrays.stream(Keyword.values())
                .filter(keyword -> keyword != Keyword.UNKNOWN)
                .forEach(keyword -> response.append("\n").append(keyword));

        return response.toString();
    }

    /**
     * Marks a task as completed.
     *
     * @param argument task number
     * @return operation result
     */
    private String markTask(String argument) {
        try {
            int index = Integer.parseInt(argument) - 1;
            deque.add(new TaskList(tasks));
            tasks.mark(index);
            storage.save(tasks.getTasks());


            return "Nice! I've marked this task as done, what's next? :\n"
                    + tasks.get(index);
        } catch (IndexOutOfBoundsException | NumberFormatException e) {
            return "I couldn’t find that task. Please choose a number from 1 to " + tasks.getSize() + ".";
        }
    }

    /**
     * Marks a task as incomplete.
     *
     * @param argument task number
     * @return operation result
     */
    private String unmarkTask(String argument) {
        try {
            int index = Integer.parseInt(argument) - 1;
            deque.add(new TaskList(tasks));
            tasks.unmark(index);
            storage.save(tasks.getTasks());


            return "OK, I've marked this task as not done yet, make up your mind next time:\n"
                    + tasks.get(index);
        } catch (IndexOutOfBoundsException | NumberFormatException e) {
            return "I couldn’t find that task. Please choose a number from 1 to " + tasks.getSize() + ".";
        }
    }

    /**
     * Adds a todo task.
     *
     * @param description task description
     * @return operation result
     */
    private String addTodo(String description) {
        if (description.isBlank()) {
            return "No worries! A todo needs a description. Please try again.";
        }

        Task newTask = new ToDo(description);
        deque.add(new TaskList(tasks));
        tasks.add(newTask);
        storage.save(tasks.getTasks());


        return "Got it. I've added this task:\n" + newTask
                + "\nNow you have " + tasks.getSize() + " tasks in the list.";
    }

    /**
     * Adds a deadline task.
     *
     * @param details deadline details
     * @return operation result
     */
    private String addDeadline(String details) {
        try {
            String[] due = details.split(" /by ", 2);

            if (due.length < 2 || due[0].isBlank() || due[1].isBlank()) {
                throw new MinervaArgumentException("A deadline needs both a description and a due date. Please try again.");
            }

            Task newTask = new Deadline(due[0], due[1]);
            deque.add(new TaskList(tasks));
            tasks.add(newTask);
            storage.save(tasks.getTasks());


            return "Got it. I've added this task:\n" + newTask
                    + "\nNow you have " + tasks.getSize() + " tasks in the list.";
        } catch (MinervaArgumentException e) {
            return e.getMessage();
        } catch (java.time.format.DateTimeParseException e) {
            return "That date format didn’t work. Please use yyyy-MM-dd, such as 2026-08-27.";
        }
    }

    /**
     * Adds an event task.
     *
     * @param details event details
     * @return operation result
     */
    private String addEvent(String details) {
        try {
            String[] fromTo = details.split(" /from | /to ", 3);

            if (fromTo.length < 3 || fromTo[0].isBlank()
                    || fromTo[1].isBlank() || fromTo[2].isBlank()) {
                throw new MinervaArgumentException("An event needs a description, a start time, and an end time. Please try again.");
            }

            Task newTask = new Event(fromTo[0], fromTo[1], fromTo[2]);
            deque.add(new TaskList(tasks));
            tasks.add(newTask);
            storage.save(tasks.getTasks());


            return "Got it. I've added this task:\n" + newTask
                    + "\nNow you have " + tasks.getSize() + " tasks in the list.";
        } catch (MinervaArgumentException e) {
            return e.getMessage();
        } catch (java.time.format.DateTimeParseException e) {
            return "That start-date format didn’t work. Please use yyyy-MM-dd, such as 2026-08-27.";
        }
    }

    /**
     * Deletes a task.
     *
     * @param argument task number
     * @return operation result
     */
    private String deleteTask(String argument) {
        try {
            int index = Integer.parseInt(argument) - 1;
            deque.add(new TaskList(tasks));
            Task removed = tasks.delete(index);
            storage.save(tasks.getTasks());


            return "Noted. I've removed this task:\n" + removed
                    + "\nNow you have " + tasks.getSize() + " tasks in the list.";
        } catch (IndexOutOfBoundsException | NumberFormatException e) {
            return "I couldn’t find that task. Please choose a number from 1 to " + tasks.getSize() + ".";
        }
    }

    /**
     * Adds a generic task.
     *
     * @param command complete command
     * @return operation result
     */
    private String addTask(String command) {
        if (command.length() <= 4 || command.substring(4).isBlank()) {
            return "No worries! A task needs a description. Please try again.";
        }

        String description = command.substring(4).trim();
        Task newTask = new Task(description);
        deque.add(new TaskList(tasks));
        tasks.add(newTask);
        storage.save(tasks.getTasks());


        return "added: " + description + " as Task at index: " + tasks.getSize();
    }

    /**
     * Undoes to previous state if available.
     * @return operation result
     */
    private String undo() {
        try {
            tasks = deque.removeLast();
            storage.save(tasks.getTasks());
            return "Alright, I've undone the previous valid operation. Current state: <3 \n"
                    + listTasks();
        } catch (NoSuchElementException e) {
            return "There’s nothing to undo yet, but I’m ready when you are.";
        }
    }

    /**
     * Starts the console application.
     *
     * @param args command-line arguments
     */
    public static void main(String[] args) {
        new Minerva(FILE_PATH).run();
    }
}
