package minerva;

import java.io.File;
import java.io.FileNotFoundException;

import minerva.common.Keyword;
import minerva.exception.MinervaArgumentException;
import minerva.storage.Storage;
import minerva.task.Deadline;
import minerva.task.Event;
import minerva.task.Task;
import minerva.task.TaskList;
import minerva.task.ToDo;
import minerva.ui.Ui;

/**
 * Manages Minerva commands and task storage.
 */
public class Minerva {
    private static final String FILE_PATH = "." + File.separator + "data"
            + File.separator + "minerva.txt";

    private final Storage storage;
    private TaskList tasks;
    private TaskList foundTasks;
    private final Ui ui;

    /**
     * Loads saved tasks from the specified file.
     *
     * @param filePath path of the task storage file
     */
    public Minerva(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);

        try {
            tasks = new TaskList(storage.load());
        } catch (FileNotFoundException e) {
            ui.showLoadingError();
            tasks = new TaskList();
        }
    }

    /**
     * Processes one command for the graphical interface.
     *
     * @param input command entered by the user
     * @return response to display
     */
    public String getResponse(String input) {
        return processCommand(input);
    }

    /**
     * Processes one Minerva command and returns its response.
     *
     * @param input command entered by the user
     * @return response generated by the command
     */
    public String processCommand(String input) {
        if (input == null || input.isBlank()) {
            return "Please enter a command.";
        }

        String fullCommand = input.trim();
        String[] parts = fullCommand.split("\\s+", 2);
        String command = parts[0].toLowerCase();

        Keyword keyword = switch (command) {
            case "bye" -> Keyword.BYE;
            case "list" -> Keyword.LIST;
            case "mark" -> Keyword.MARK;
            case "unmark" -> Keyword.UNMARK;
            case "todo" -> Keyword.TODO;
            case "deadline" -> Keyword.DEADLINE;
            case "event" -> Keyword.EVENT;
            case "delete" -> Keyword.DELETE;
            case "task" -> Keyword.TASK;
            case "help" -> Keyword.HELP;
            case "find" -> Keyword.FIND;
            default -> Keyword.UNKNOWN;
        };

        String argument = parts.length > 1 ? parts[1].trim() : "";

        return switch (keyword) {
            case BYE -> "Bye. And I hope to see you again soon!";

            case LIST -> listTasks();

            case FIND -> findTasks(argument);

            case HELP -> showHelp();

            case MARK -> markTask(argument);

            case UNMARK -> unmarkTask(argument);

            case TODO -> addTodo(argument);

            case DEADLINE -> addDeadline(argument);

            case EVENT -> addEvent(argument);

            case DELETE -> deleteTask(argument);

            case TASK -> addTask(fullCommand);

            case UNKNOWN -> "OOPS!!! I'm sorry, but I don't know what that means :-(";
        };
    }

    /**
     * Runs the console version of Minerva.
     */
    public void run() {
        ui.showWelcome();
        boolean isExit = false;

        while (!isExit) {
            ui.showPrompt();
            String command = ui.readCommand();
            String response = processCommand(command);
            ui.showMessage(response);
            isExit = command.trim().equalsIgnoreCase("bye");
        }
    }

    /**
     * Lists all stored tasks.
     *
     * @return formatted task list
     */
    private String listTasks() {
        StringBuilder response = new StringBuilder("Here are the tasks in your list:");

        for (int i = 0; i < tasks.getSize(); i++) {
            response.append("\n").append(i + 1).append(". ").append(tasks.get(i));
        }

        return response.toString();
    }

    /**
     * Finds tasks containing the specified word.
     *
     * @param word search term
     * @return matching tasks
     */
    private String findTasks(String word) {
        if (word.isBlank()) {
            return "Please provide a word to search for.";
        }

        foundTasks = new TaskList();

        for (int i = 0; i < tasks.getSize(); i++) {
            if (tasks.get(i).containsWord(word)) {
                foundTasks.add(tasks.get(i));
            }
        }

        StringBuilder response = new StringBuilder(
                "Here are the matching tasks in your list:\n"
                        + "Please do not delete/mark/unmark with this found index");

        for (int i = 0; i < foundTasks.getSize(); i++) {
            response.append("\n").append(i + 1).append(".").append(foundTasks.get(i));
        }

        return response.toString();
    }

    /**
     * Lists all available commands.
     *
     * @return available commands
     */
    private String showHelp() {
        StringBuilder response = new StringBuilder("Here are the available functions:");

        for (Keyword keyword : Keyword.values()) {
            if (keyword != Keyword.UNKNOWN) {
                response.append("\n").append(keyword);
            }
        }

        return response.toString();
    }

    /**
     * Marks a task as completed.
     *
     * @param argument task number
     * @return operation result
     */
    private String markTask(String argument) {
        try {
            int index = Integer.parseInt(argument) - 1;
            tasks.mark(index);
            storage.save(tasks.getTasks());

            return "Nice! I've marked this task as done, what's next? :\n"
                    + tasks.get(index);
        } catch (IndexOutOfBoundsException | NumberFormatException e) {
            return "mark needs a valid number less than or equals to: " + tasks.getSize();
        }
    }

    /**
     * Marks a task as incomplete.
     *
     * @param argument task number
     * @return operation result
     */
    private String unmarkTask(String argument) {
        try {
            int index = Integer.parseInt(argument) - 1;
            tasks.unmark(index);
            storage.save(tasks.getTasks());

            return "OK, I've marked this task as not done yet, make up your mind next time:\n"
                    + tasks.get(index);
        } catch (IndexOutOfBoundsException | NumberFormatException e) {
            return "unmark needs a valid number less than or equals to: " + tasks.getSize();
        }
    }

    /**
     * Adds a todo task.
     *
     * @param description task description
     * @return operation result
     */
    private String addTodo(String description) {
        if (description.isBlank()) {
            return "OOPS!!! The description of a todo cannot be empty.";
        }

        Task newTask = new ToDo(description);
        tasks.add(newTask);
        storage.save(tasks.getTasks());

        return "Got it. I've added this task:\n" + newTask
                + "\nNow you have " + tasks.getSize() + " tasks in the list.";
    }

    /**
     * Adds a deadline task.
     *
     * @param details deadline details
     * @return operation result
     */
    private String addDeadline(String details) {
        try {
            String[] due = details.split(" /by ", 2);

            if (due.length < 2 || due[0].isBlank() || due[1].isBlank()) {
                throw new MinervaArgumentException("Deadline has no due date!!!!");
            }

            Task newTask = new Deadline(due[0], due[1]);
            tasks.add(newTask);
            storage.save(tasks.getTasks());

            return "Got it. I've added this task:\n" + newTask
                    + "\nNow you have " + tasks.getSize() + " tasks in the list.";
        } catch (MinervaArgumentException e) {
            return e.getMessage();
        } catch (java.time.format.DateTimeParseException e) {
            return "Please enter date in yyyy-MM-dd format! (e.g., 2026-08-27)";
        }
    }

    /**
     * Adds an event task.
     *
     * @param details event details
     * @return operation result
     */
    private String addEvent(String details) {
        try {
            String[] fromTo = details.split(" /from | /to ", 3);

            if (fromTo.length < 3 || fromTo[0].isBlank()
                    || fromTo[1].isBlank() || fromTo[2].isBlank()) {
                throw new MinervaArgumentException("Missing from or to fields, check again!");
            }

            Task newTask = new Event(fromTo[0], fromTo[1], fromTo[2]);
            tasks.add(newTask);
            storage.save(tasks.getTasks());

            return "Got it. I've added this task:\n" + newTask
                    + "\nNow you have " + tasks.getSize() + " tasks in the list.";
        } catch (MinervaArgumentException e) {
            return e.getMessage();
        } catch (java.time.format.DateTimeParseException e) {
            return "Please enter the 'from' date in yyyy-MM-dd format!"
                    + " (e.g., 2026-08-27)";
        }
    }

    /**
     * Deletes a task.
     *
     * @param argument task number
     * @return operation result
     */
    private String deleteTask(String argument) {
        try {
            int index = Integer.parseInt(argument) - 1;
            Task removed = tasks.delete(index);
            storage.save(tasks.getTasks());

            return "Noted. I've removed this task:\n" + removed
                    + "\nNow you have " + tasks.getSize() + " tasks in the list.";
        } catch (IndexOutOfBoundsException | NumberFormatException e) {
            return "delete needs a valid number less than or equals to: " + tasks.getSize();
        }
    }

    /**
     * Adds a generic task.
     *
     * @param command complete command
     * @return operation result
     */
    private String addTask(String command) {
        if (command.length() <= 4 || command.substring(4).isBlank()) {
            return "Sorry no blanks allowed !!";
        }

        String description = command.substring(4).trim();
        Task newTask = new Task(description);
        tasks.add(newTask);
        storage.save(tasks.getTasks());

        return "added: " + description + " as Task at index: " + tasks.getSize();
    }

    /**
     * Starts the console application.
     *
     * @param args command-line arguments
     */
    public static void main(String[] args) {
        new Minerva(FILE_PATH).run();
    }
}